# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clock_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QFont
from PyQt5.QtCore import QSize, QTimer, QTime, Qt, pyqtSignal


class Ui_Form(QtWidgets.QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(678, 489)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.appTab = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appTab.sizePolicy().hasHeightForWidth())
        self.appTab.setSizePolicy(sizePolicy)
        self.appTab.setObjectName("appTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clockLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(72)
        self.clockLabel.setFont(font)
        self.clockLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.clockLabel.setObjectName("clockLabel")
        self.horizontalLayout.addWidget(self.clockLabel)
        self.appTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.addMinuteButton = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addMinuteButton.sizePolicy().hasHeightForWidth())
        self.addMinuteButton.setSizePolicy(sizePolicy)
        self.addMinuteButton.setMinimumSize(QtCore.QSize(80, 80))
        self.addMinuteButton.setText("")
        self.addMinuteButton.setObjectName("addMinuteButton")
        self.horizontalLayout_7.addWidget(self.addMinuteButton)
        self.addHourButton = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addHourButton.sizePolicy().hasHeightForWidth())
        self.addHourButton.setSizePolicy(sizePolicy)
        self.addHourButton.setMinimumSize(QtCore.QSize(80, 80))
        self.addHourButton.setText("")
        self.addHourButton.setObjectName("addHourButton")
        self.horizontalLayout_7.addWidget(self.addHourButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.stopwatchLabel = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(72)
        self.stopwatchLabel.setFont(font)
        self.stopwatchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stopwatchLabel.setObjectName("stopwatchLabel")
        self.verticalLayout_3.addWidget(self.stopwatchLabel)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.takeHourButton = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.takeHourButton.sizePolicy().hasHeightForWidth())
        self.takeHourButton.setSizePolicy(sizePolicy)
        self.takeHourButton.setMinimumSize(QtCore.QSize(80, 80))
        self.takeHourButton.setText("")
        self.takeHourButton.setObjectName("takeHourButton")
        self.horizontalLayout_6.addWidget(self.takeHourButton)
        self.takeMinuteButton = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.takeMinuteButton.sizePolicy().hasHeightForWidth())
        self.takeMinuteButton.setSizePolicy(sizePolicy)
        self.takeMinuteButton.setMinimumSize(QtCore.QSize(80, 80))
        self.takeMinuteButton.setText("")
        self.takeMinuteButton.setObjectName("takeMinuteButton")
        self.horizontalLayout_6.addWidget(self.takeMinuteButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.appTab.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toDoListView = QtWidgets.QListView(self.tab_3)
        self.toDoListView.setObjectName("toDoListView")
        self.verticalLayout_2.addWidget(self.toDoListView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.toDoAddButton = QtWidgets.QPushButton(self.tab_3)
        self.toDoAddButton.setObjectName("toDoAddButton")
        self.horizontalLayout_2.addWidget(self.toDoAddButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.toDoRemoveButton = QtWidgets.QPushButton(self.tab_3)
        self.toDoRemoveButton.setObjectName("toDoRemoveButton")
        self.horizontalLayout_2.addWidget(self.toDoRemoveButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.appTab.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.memoTab = QtWidgets.QTabWidget(self.tab_4)
        self.memoTab.setObjectName("memoTab")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.memoTab.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.memoTab.addTab(self.tab_6, "")
        self.verticalLayout_5.addWidget(self.memoTab)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.addMemoButton = QtWidgets.QPushButton(self.tab_4)
        self.addMemoButton.setObjectName("addMemoButton")
        self.horizontalLayout_9.addWidget(self.addMemoButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.removeMemoButton = QtWidgets.QPushButton(self.tab_4)
        self.removeMemoButton.setObjectName("removeMemoButton")
        self.horizontalLayout_9.addWidget(self.removeMemoButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.appTab.addTab(self.tab_4, "")
        self.verticalLayout_4.addWidget(self.appTab)

        self.addHourButton.setIcon(QIcon("arrow_up.png"))
        self.addHourButton.setIconSize(QSize(80, 80))
        self.addHourButton.setStyleSheet("QPushButton{background:transparent;}")
        self.addHourButton.pressed.connect(lambda: self.pressed_up(self.addHourButton))
        self.addHourButton.released.connect(lambda: self.released_up(self.addHourButton))
        self.addMinuteButton.setIcon(QIcon("arrow_up.png"))
        self.addMinuteButton.setIconSize(QSize(80, 80))
        self.addMinuteButton.setStyleSheet("QPushButton{background:transparent;}")
        self.addMinuteButton.pressed.connect(lambda: self.pressed_up(self.addMinuteButton))
        self.addMinuteButton.released.connect(lambda: self.released_up(self.addMinuteButton))
        self.takeHourButton.setIcon(QIcon("arrow_down.png"))
        self.takeHourButton.setIconSize(QSize(80, 80))
        self.takeHourButton.setStyleSheet("QPushButton{background:transparent;}")
        self.takeHourButton.pressed.connect(lambda: self.pressed_down(self.takeHourButton))
        self.takeHourButton.released.connect(lambda: self.released_down(self.takeHourButton))
        self.takeMinuteButton.setIcon(QIcon("arrow_down.png"))
        self.takeMinuteButton.setIconSize(QSize(80, 80))
        self.takeMinuteButton.setStyleSheet("QPushButton{background:transparent;}")
        self.takeMinuteButton.pressed.connect(lambda: self.pressed_down(self.takeMinuteButton))
        self.takeMinuteButton.released.connect(lambda: self.released_down(self.takeMinuteButton))

        timer = QTimer(self)
        timer.timeout.connect(lambda: self.displayTime(self.stopwatchLabel))
        timer.timeout.connect(lambda: self.displayTime(self.clockLabel))
        timer.start(1000)


        self.retranslateUi(Form)
        self.appTab.setCurrentIndex(1)
        self.memoTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.displayTime(self.clockLabel)
        self.appTab.setTabText(self.appTab.indexOf(self.tab), _translate("Form", "Clock"))
        self.displayTime(self.stopwatchLabel)
        self.appTab.setTabText(self.appTab.indexOf(self.tab_2), _translate("Form", "Stop Watch"))
        self.toDoAddButton.setText(_translate("Form", "Add"))
        self.toDoRemoveButton.setText(_translate("Form", "Remove"))
        self.appTab.setTabText(self.appTab.indexOf(self.tab_3), _translate("Form", "To Do"))
        self.memoTab.setTabText(self.memoTab.indexOf(self.tab_5), _translate("Form", "Memo 1"))
        self.memoTab.setTabText(self.memoTab.indexOf(self.tab_6), _translate("Form", "Memo 2"))
        self.addMemoButton.setText(_translate("Form", "Add"))
        self.removeMemoButton.setText(_translate("Form", "Remove"))
        self.appTab.setTabText(self.appTab.indexOf(self.tab_4), _translate("Form", "Memo"))

    def pressed_up(self, obj):
        if obj == self.addHourButton:
            self.addHourButton.setIcon(QIcon("arrow_up_pressed.png"))
        elif obj == self.addMinuteButton:
            self.addMinuteButton.setIcon(QIcon("arrow_up_pressed.png"))
        else:
            raise TypeError("Object Error")

    def released_up(self, obj):
        if obj == self.addHourButton:
            self.addHourButton.setIcon(QIcon("arrow_up.png"))
        elif obj == self.addMinuteButton:
            self.addMinuteButton.setIcon(QIcon("arrow_up.png"))
        else:
            raise TypeError("Object Error")

    def pressed_down(self, obj):
        if obj == self.takeHourButton:
            self.takeHourButton.setIcon(QIcon("arrow_down_pressed.png"))
        elif obj == self.takeMinuteButton:
            self.takeMinuteButton.setIcon(QIcon("arrow_down_pressed.png"))
        else:
            raise TypeError("Object Error")

    def released_down(self, obj):
        if obj == self.takeHourButton:
            self.takeHourButton.setIcon(QIcon("arrow_down.png"))
        elif obj == self.takeMinuteButton:
            self.takeMinuteButton.setIcon(QIcon("arrow_down.png"))
        else:
            raise TypeError("Object Error")

    def displayTime(self, label):
        currentTime = QTime.currentTime()

        displayText = currentTime.toString("hh:mm:ss")
        print(displayText)

        label.setText(displayText)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
